[project]
name = "yet-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-camera>=2023.1.7",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.3",
    "pygame>=2.6.1",
    "scikit-learn>=1.7.2",
]
